heat_template_version: 2013-05-23

description: HOT file sets up OpenStack Swift-All-In-One and ZeroVM with ZeroCloud middleware and Swift-Browser

parameters:
  image:
    type: string
    default: Ubuntu 14.04
    description: Base image for ZeroCloud
  key_name:
    type: string
    default: zerocloud_key
    description: SSH public key name
  key_contents:
    type: string
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/EMiCSewfa6TRHM/XtJDlIlFu4cGmX0YlfGu4Y93obrOXsBFMjePnWiGVivTdJ8QH48PbAhztoAj1MT2vxj2uf/0nu8Zz0bjZh4lJyZ9jZHxnkOQ+JYxJtC+pu9GYANbQ7C3ccxmHur88gJdkZ0/auTW9aghTy+q4sDnK1rQ/Dss3euLw4lqEDfg2Ebau71jHPF1Ta1Fegf5M6PbNDP4sud0Z0xIOK1cP8kLE4uKGoeCcwGwEentJpnHH3yB2NvyY4TXBRj7hkRvSiwWEKl5+F66134Acej9qI/DlpcFi6ZkXXQBCYnLh6swJ39ozX2xFe+R0ZHrnEY/befltK4wJ sina@kumosan
    description: SSH public key contents
  internal_network_name:
    type: string
    description: The name of the internal network
    default: internalnet
  internal_network_cidr:
    type: string
    description: The CIDR of the internal network
    default: 10.210.211.0/24
  internal_gw_name:
    type: string
    description: The name of the internal network router
    default: internalrouter
  internal_dns_primary:
    type: string
    description: Primary DNS for internal network
    default: 8.8.8.8
  internal_dns_secondary:
    type: string
    description: Secondary DNS for internal network
    default: 8.8.4.4
  public_network_name:
    type: string
    description: The UUID of the public network
    default: 87cb4819-182e-4f2d-86d2-6970c11962da

resources:

   internal_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: internal_network_name }

   internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: internal_net }
      cidr: { get_param: internal_network_cidr }
      name: { get_param: internal_network_name }
      dns_nameservers: [ { get_param: internal_dns_primary }, { get_param: internal_dns_secondary } ]

   internal_router:
    type: OS::Neutron::Router
    properties:
      name: { get_param: internal_gw_name }

   internal_router_extgw:
    type: OS::Neutron::RouterGateway
    properties:
      network_id: { get_param: public_network_name }
      router_id: { get_resource: internal_router }

   internal_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: internal_router }
      subnet_id: { get_resource: internal_subnet }

   zerocloud_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: zerocloud
      description: Allows all out and SSH in
      rules: [ {"direction": egress,
                "remote_ip_prefix": 0.0.0.0/0,
                "port_range_min": 1,
                "port_range_max": 65535,
                "ethertype": IPv4,
                "protocol": tcp},
               {"direction": egress,
                "remote_ip_prefix": 0.0.0.0/0,
                "port_range_min": 1,
                "port_range_max": 65535,
                "ethertype": IPv4,
                "protocol": udp},
               {"direction": ingress,
                "remote_ip_prefix": 0.0.0.0/0,
                "port_range_min": 22,
                "port_range_max": 22,
                "ethertype": IPv4,
                "protocol": tcp}]

   zerocloud_key:
    type: OS::Nova::KeyPair
    properties:
      name: zerocloud_key
      public_key: { get_param: key_contents }
      save_private_key: False

   zerocloud01_internal_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: internal_net }
      fixed_ips:
        - subnet_id: { get_resource: internal_subnet  }
      security_groups:
        - { get_resource: zerocloud_secgroup }

   zerocloud01_floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_network_name }

   zerocloud01_floatingip_ass:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: zerocloud01_floatingip }
      port_id: { get_resource: zerocloud01_internal_port }
    depends_on:
      - internal_router_interface
      - internal_router_extgw
      - zerocloud01_internal_port

   zerocloud01:
    type: OS::Nova::Server
    depends_on: [ zerocloud01_internal_port ]
    properties:
      name: zerocloud01
      image: { get_param: image}
      flavor: m1.xlarge
      key_name: { get_resource: zerocloud_key } 
      networks:
        - port: { get_resource: zerocloud01_internal_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: cloud-config.yaml }
          params:
            $ssh_key: { get_attr: [ zerocloud_key, public_key ] }
            $private_ip: { get_attr: [ zerocloud01_internal_port, fixed_ips, 0, ip_address ] }

outputs:
  public_ip:
    description: ZeroCloud Cluster SSH Access IP
    value: { get_attr: [ zerocloud01_floatingip, floating_ip_address ] }
